### ISSUE TITLE
 External trigger for "static int fan_read ()

### ISSUE THREAD

**Issue by vvrec** [Brawrdon/esp-homekit-arduino-sdk#7]
Thank you! Everything works perfectly! Could you add a real external trigger for "static int fan_read ()" to the example. I just can't use the callback correctly. Only obtained using a queue in thread_entry.

**Comment by Brawrdon** [comment]
I have a more concrete implementation of the library in my personal project. You can see it in this branch, hopefully this helps! https://github.com/Brawrdon/PlantKit/tree/sensor-integration
