### ISSUE TITLE
How to change switch state in app?

### ISSUE THREAD

**Issue by JosuaK03** [Brawrdon/esp-homekit-arduino-sdk#8]
Hi,
First, thank you for this library!

Can you explain, how to update the value in the HomeKit-App?
My plan is to update the switch state in the app, when a physically button action is detected.
I am not sure, how to run the read-method from e.g. loop(), or am I on the wrong track there?

Thank you!

**Comment by Brawrdon** [comment]
The value is updated in HomeKit by calling the `hap_char_update_val(characteristic, value)` function which you can use anywhere. It takes a pointer to the characteristic you want to update and a pointer to the value you want to send. You can see an example in my other project: https://github.com/Brawrdon/PlantKit/blob/b44446a7730ef7ae3b0acce52f2ac94aba818298/src/PlantKit.cpp#L34

Here's a messy explanation based on the function in the example. I'm assuming you've setup the HomeKit service with a switch characteristic.

1. Create a global variable to hold a pointer to the service created during setup. It makes life so much easier.
2. Set whatever it is you need to set to run code when a button press is detected. You can do this in the `loop()` method for example.
3. Get the characteristic pointer with the function `hap_serv_get_char_by_uuid(service, UUID_CURRENT_FOR_CHARACTERISTIC)`.
4. Create a `hap_val_t` object with `.b` (boolean) attribute and set its value depending on the switch state.
5. Call `hap_char_update_val(characteristic, value)`.

You can dig more out by reading the source code of the original library (https://github.com/espressif/esp-homekit-sdk/blob/c62f64dea6669547182e932dfded0a3a912a1951/components/homekit/esp_hap_core/include/hap.h#L1028), it has good documentation for each function in the code comments. I still plan to add some Arduino style wrappers to make these things easier, just don't have the time right now!

**Comment by JosuaK03** [comment]
Thank you for the very helpful and quick response.

Now it's working!

All the best!

**Comment by Brawrdon** [comment]
No worries! Would love to see what you make with it! 😄
